name: etc_test_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.2
  ffmpeg_kit_flutter: 6.0.3-LTS
  get: ^4.6.6
  dio: ^5.4.0
  flutter_screenutil: ^5.9.0
  permission_handler: ^11.3.0
  flutter_blue_plus: ^1.31.15
  rxdart: ^0.27.7
  flutter_reactive_ble: ^5.3.1
  geofence_service: ^5.0.0
  background_locator_2: ^2.0.6
  flutter_background: ^1.2.0
  flutter_regex: ^0.0.3
  intl: ^0.19.0
  xml: ^6.5.0
  translator: ^1.0.0
  flutter_tesseract_ocr: ^0.4.24
  flutter_scalable_ocr: ^2.0.0
  image_picker: ^1.0.8
  excel: ^4.0.3
  cached_network_image: ^3.3.1
  http_parser: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/tessdata/
    - assets/tessdata_config.json

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
